### ISSUE TITLE
Ne mogu instalirati plugin (plugin dont work?)

### ISSUE THREAD

**Issue by githubnagib** [zoran-cuckovic/QGIS-topographic-networks#2]
Zorane, ovaj plugin ne mogu instalirati u verziji qgis 2.12.1 - Lyon.
Javi se neka greška:
"This plugin is broken
No module named resources_rc"
(Zoran, this plugin can not be installed in version 2.12.1 qgis - Lyon.)
msbox error:
"This plugin is broken
No module named resources_rc"

**Comment by stevefaeembra** [comment]
i get this message too - I found I could take out the line **import resources_rc** and restart QGIS, then re-enable the plugin from plugin manager, and it works.

**Comment by githubnagib** [comment]
Same again?!

Couldn't load plugin TopographicNetworks due to an error when calling its classFactory() method

**Comment by stevefaeembra** [comment]
are you on windows, mac or linux? i'm on ubuntu, and qgis 2.14.1. That patch worked for me but I've not had a chance to check if it works on Windows.

**Comment by zoran-cuckovic** [comment]
Hello!
I don't handle well Qt and all that stuff... Yes you can just **comment out line 31** in topographic_networks.py `import resources_rc`. I updated the repository and resubmitted the plugin.
